[2022-04-19 05:08:28] ERROR|django.request|Internal Server Error: /api/task-list/
Traceback (most recent call last):
  File "/home/preetham/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/preetham/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/preetham/SAD-Final/todoapp/api/views.py", line 114, in taskList
    payload = jwt.decode(token, 'secret-app-key', algorithms=['HS256'])
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 90, in decode_complete
    decoded = api_jws.decode_complete(
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 149, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 187, in _load
    raise DecodeError(f"Invalid token type. Token must be a {bytes}")
jwt.exceptions.DecodeError: Invalid token type. Token must be a <class 'bytes'>
[2022-04-19 07:35:19] INFO|django.utils.autoreload|Watching for file changes with StatReloader
[2022-04-19 07:35:27] WARNING|django.request|Forbidden: /api/current-user/
[2022-04-19 07:35:27] ERROR|django.request|Internal Server Error: /api/task-list/
Traceback (most recent call last):
  File "/home/preetham/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/preetham/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/preetham/SAD-Final/todoapp/api/views.py", line 114, in taskList
    payload = jwt.decode(token, 'secret-app-key', algorithms=['HS256'])
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 90, in decode_complete
    decoded = api_jws.decode_complete(
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 149, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 187, in _load
    raise DecodeError(f"Invalid token type. Token must be a {bytes}")
jwt.exceptions.DecodeError: Invalid token type. Token must be a <class 'bytes'>
[2022-04-19 07:36:02] INFO|django.utils.autoreload|Watching for file changes with StatReloader
[2022-04-19 07:37:27] WARNING|django.request|Forbidden: /api/task-delete/4/
[2022-04-19 07:37:32] WARNING|django.request|Forbidden: /api/task-delete/4/
[2022-04-19 08:45:14] INFO|django.utils.autoreload|Watching for file changes with StatReloader
[2022-04-19 09:15:32] INFO|django.utils.autoreload|Watching for file changes with StatReloader
[2022-04-19 09:15:44] WARNING|django.request|Forbidden: /api/current-user/
[2022-04-19 09:15:44] ERROR|django.request|Internal Server Error: /api/task-list/
Traceback (most recent call last):
  File "/home/preetham/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/preetham/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/preetham/SAD-Final/todoapp/api/views.py", line 114, in taskList
    payload = jwt.decode(token, 'secret-app-key', algorithms=['HS256'])
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 90, in decode_complete
    decoded = api_jws.decode_complete(
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 149, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/home/preetham/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 187, in _load
    raise DecodeError(f"Invalid token type. Token must be a {bytes}")
jwt.exceptions.DecodeError: Invalid token type. Token must be a <class 'bytes'>
[2022-04-19 09:16:47] WARNING|django.request|Forbidden: /api/user-login/
[2022-04-19 09:16:52] WARNING|django.request|Forbidden: /api/user-login/
[2022-04-19 09:16:55] WARNING|django.request|Forbidden: /api/user-login/
[2022-04-19 09:17:01] WARNING|django.request|Forbidden: /api/user-login/
[2022-04-19 09:17:05] WARNING|django.request|Forbidden: /api/user-login/
[2022-04-19 09:17:10] WARNING|django.request|Forbidden: /api/user-login/
[2022-04-19 09:17:16] WARNING|django.request|Forbidden: /api/user-login/
[2022-04-19 09:17:23] WARNING|django.request|Forbidden: /api/user-login/
[2022-04-19 09:17:46] WARNING|django.request|Forbidden: /api/task-delete/1/
[2022-04-19 09:17:50] WARNING|django.request|Forbidden: /api/task-delete/1/
